vchumack/petsSupport_front

src/components/Reuse/Title/Subtitle.jsx, src/components/Reuse/Title/Subtitle.module.scss, src/components/Reuse/Title/Title.jsx, src/components/Reuse/Title/Title.module.scss, src/shared/styles/_mixins.scss, src/shared/styles/_variables.scss
fixed media mixins, edited title component, added subtitle component
=> 19 fix mixins

src/components/Notices/addPet/NoticesAddPet.jsx, src/components/Notices/addPet/NoticesAddPet.module.scss, src/components/Notices/items/NoticesItems.module.scss, src/pages/NoticesPage/NoticesPage.jsx, src/pages/NoticesPage/NoticesPage.module.scss
=> add button

src/components/Reuse/Modal/Modal.module.scss, src/pages/HomePage/HomePage.jsx
=> Fix circle btn

src/components/Reuse/Button/Button.jsx, src/components/Reuse/Modal/Modal.jsx, src/pages/HomePage/HomePage.jsx
=> Try fix Modal

src/components/Reuse/Button/Button.jsx, src/components/Reuse/Button/Button.module.scss, src/components/Reuse/Container/Container.jsx, src/components/Reuse/Container/Container.module.scss, src/components/Reuse/Input/Input.jsx, src/components/Reuse/Input/Input.module.scss, src/components/Reuse/Modal/Modal.jsx, src/components/Reuse/Modal/Modal.module.scss
Add mixins an fix Add btn position
=> Fix styles

src/components/Notices/addPet/NoticesAddPet.jsx, src/components/Notices/addPet/NoticesAddPet.module.scss, src/components/Notices/categories/NoticesCategories.jsx, src/components/Notices/categories/NoticesCategories.module.scss, src/components/Notices/heading/NoticesHeading.jsx, src/components/Notices/items/NoticesItems.jsx, src/components/Notices/items/NoticesItems.module.scss, src/components/Notices/search/NoticesSearch.jsx, src/components/Reuse/Container/Container.jsx, src/pages/NoticesPage/NoticesPage.jsx, src/pages/NoticesPage/NoticesPage.module.scss
=> fix Container

src/components/Notices/items/NoticesItems.jsx, src/components/Notices/list/NoticesList.jsx, src/components/Notices/list/NoticesList.module.scss, src/pages/NoticesPage/NoticesPage.jsx, src/pages/NoticesPage/NoticesPage.module.scss
=> fix List Notices

package-lock.json, src/components/Reuse/Button/Button.jsx, src/components/Reuse/Container/Container.module.scss
Container: fix padding for Desktop
Button: fix props
=> Fix components

src/components/Notices/addPet/NoticesAddPet.jsx, src/components/Notices/addPet/NoticesAddPet.module.scss, src/components/Notices/addPetForm/NoticesAddPetForm.jsx, src/components/Notices/addPetForm/NoticesAddPetForm.module.scss, src/components/Notices/addPetForm/steps/FirstStep.jsx, src/components/Notices/addPetForm/steps/SecondStep.jsx, src/components/Notices/addPetForm/steps/index.js, src/components/Notices/categories/NoticesCategories.jsx, src/components/Notices/heading/NoticesHeading.jsx, src/components/Notices/items/NoticesItems.jsx, src/components/Notices/items/NoticesItems.module.scss, src/components/Notices/list/NoticesList.module.scss, src/pages/NoticesPage/NoticesPage.jsx, src/shared/images/Notices/Notices-plusForm.svg, src/shared/images/Notices/el_female.svg, src/shared/images/Notices/el_male.svg
=> Notices page

src/components/Notices/addPetForm/NoticesAddPetForm.jsx, src/components/Notices/items/NoticesItems.jsx, src/components/Notices/items/NoticesItems.module.scss, src/components/Notices/list/NoticesList.jsx
finish styles Nitices items and learn more button
=> finish styles Nitices items and learn more button

src/components/Notices/addPet/NoticesAddPet.jsx, src/components/Notices/addPet/NoticesAddPet.module.scss, src/components/Notices/addPetForm/NoticesAddPetForm.jsx, src/components/Notices/addPetForm/NoticesAddPetForm.module.scss, src/components/Notices/addPetForm/steps/FirstStep.jsx, src/components/Notices/addPetForm/steps/SecondStep.jsx
=> 104 notices add pet

src/components/Notices/categories/NoticesCategories.module.scss, src/components/Notices/list/NoticesList.jsx, src/components/Notices/search/NoticesSearch.jsx, src/components/Notices/search/NoticesSearch.module.scss, src/components/Reuse/Modal/Modal.module.scss, src/pages/NoticesPage/NoticesPage.jsx, src/pages/NoticesPage/NoticesPage.module.scss, src/redux/notices/notices-selectors.js, src/redux/notices/notices-slice.js
=> added logic filter notices

src/components/Notices/categories/NoticesCategories.jsx, src/components/Notices/categories/NoticesCategories.module.scss, src/pages/NoticesPage/NoticesPage.jsx, src/pages/NoticesPage/NoticesPage.module.scss
=> added styles sections Notices Categoties

src/components/Notices/categories/NoticesCategories.jsx, src/components/Notices/categories/NoticesCategories.module.scss, src/components/Notices/items/NoticesItems.jsx, src/components/Notices/items/NoticesItems.module.scss, src/components/Notices/learnMore/LearnMore.jsx, src/components/Notices/learnMore/LearnMore.module.scss, src/components/Notices/list/NoticesList.jsx, src/components/Notices/list/NoticesList.module.scss
=> fix bag Notices

package-lock.json, package.json, src/components/Authorization/Input/inputOptions.js, src/components/Authorization/LoginForm/LoginForm.jsx, src/components/Authorization/RegisterForm/RegisterForm.jsx, src/components/Authorization/getAuthFormContent.js, src/components/News/NewsArticle/NewsArticle.module.scss, src/components/News/NewsHeading/NewsHeading.jsx, src/components/News/NewsHeading/NewsHeading.module.scss, src/components/News/NewsItem/NewsItem.jsx, src/components/News/helpers/formatDate.js, src/pages/NewsPage/NewsPage.jsx
fixed all problems from Valery review WITHOUT Pagination in news
=> 95 fix news

src/components/Notices/items/NoticesItems.module.scss, src/components/Notices/learnMore/LearnMore.module.scss, src/components/Notices/list/NoticesList.jsx, src/components/Notices/pagination/paginationBtn/PaginationBtn.jsx, src/components/Notices/pagination/paginationBtn/PaginationBtn.module.scss, src/components/Notices/pagination/paginationList/PaginationList.jsx, src/components/Notices/pagination/paginationList/PaginationList.module.scss, src/components/Notices/search/NoticesSearch.jsx, src/pages/NoticesPage/NoticesPage.jsx, src/redux/notices/notices-operations.js, src/redux/notices/notices-selectors.js, src/redux/notices/notices-slice.js, src/shared/api/notices.js
=> fix bug and add pagination section notice

src/components/News/Search/Search.jsx, src/components/Reuse/Pagination/PaginationBtn/PaginationBtn.jsx, src/redux/news/news-slice.js, src/shared/api/news.js
=> fixed news pagination, added totalPages dynamic logic

src/components/News/NewsEmpty/NewsEmpty.jsx, src/components/News/NewsEmpty/NewsEmpty.module.scss, src/components/News/NewsHeading/NewsHeading.module.scss, src/components/News/Search/Search.jsx, src/components/News/Search/Search.module.scss, src/components/News/Search/SearchBtns/SearchBtns.jsx, src/components/News/Search/SearchBtns/SearchBtns.module.scss, src/components/News/Search/SearchTooltip.jsx, src/pages/NewsPage/NewsPage.jsx, src/redux/news/news-slice.js, src/shared/api/news.js
Fixed news search
Added tooltip
Added empty message
=> 196 fix news search

src/components/Notices/items/NoticesItems.jsx, src/components/Notices/items/NoticesItems.module.scss, src/components/Notices/learnMore/LearnMore.module.scss, src/components/Notices/list/NoticesList.jsx, src/components/Notices/list/NoticesList.module.scss, src/components/Notices/pagination/paginationList/PaginationList.module.scss, src/redux/notices/notices-selectors.js, src/redux/notices/notices-slice.js
=> fix bag sections noticis

src/components/Notices/list/NoticesList.jsx, src/components/Notices/pagination/paginationBtn/PaginationBtn.jsx, src/pages/NoticesPage/NoticesPage.jsx, src/pages/NoticesPage/NoticesPage.module.scss, src/redux/notices/notices-operations.js, src/redux/notices/notices-selectors.js, src/redux/notices/notices-slice.js, src/shared/api/notices.js
fixed notices sell, lost, hands categories pagination
!!! NOT FIXED favorite and my ads pagination
=> 211 fix fixing

src/components/Notices/list/NoticesList.jsx
removed pagination from notices favorite and own categories
=> removed pagination from notices favorite and own categories

src/components/Notices/list/NoticesList.jsx, src/components/Notices/pagination/paginationBtn/PaginationBtn.jsx, src/components/Notices/search/NoticesSearch.jsx, src/pages/NoticesPage/NoticesPage.jsx, src/redux/notices/notices-operations.js, src/redux/notices/notices-selectors.js, src/redux/notices/notices-slice.js, src/redux/store.js, src/shared/api/notices.js
Added normal search to notices sell, lost and hands categories
added empty notification to notice page
=> 200 fix notices search

src/pages/HomePage/HomePage.jsx, src/pages/HomePage/HomePage.module.scss
Simple animation + some work with screen are done.
=> 215 add animation to hero

src/components/Notices/items/NoticesItems.jsx, src/components/Notices/learnMore/LearnMore.jsx, src/components/Notices/list/NoticesList.jsx, src/components/Notices/pagination/paginationBtn/PaginationBtn.jsx, src/components/Notices/search/NoticesSearch.jsx, src/redux/notices/notices-operations.js, src/redux/notices/notices-selectors.js, src/redux/notices/notices-slice.js, src/shared/api/notices.js
Fixed notices on empty own list refresh when adding a new pet
Refactored getQueryParams destructr
fixed learn more modal add/remove from favorite bug
=> 228 task just in case

src/App.js, src/components/Notices/addPetForm/steps/FirstStep.jsx, src/components/Notices/addPetForm/steps/SecondStep.jsx, src/components/Notices/categories/NoticesCategories.module.scss, src/components/Notices/items/NoticesItems.jsx, src/components/Notices/items/NoticesItems.module.scss, src/components/Notices/learnMore/Buttons/ContactBtn/ContactBtn.jsx, src/components/Notices/learnMore/LearnMore.jsx, src/components/Notices/learnMore/LearnMore.module.scss, src/components/Notices/list/NoticesList.jsx, src/components/Notices/list/NoticesList.module.scss, src/components/Notices/pagination/paginationList/PaginationList.jsx, src/components/Notices/pagination/paginationList/PaginationList.module.scss, src/pages/NoticesPage/NoticesPage.jsx, src/pages/NoticesPage/NoticesPage.module.scss, src/redux/notices/notices-selectors.js, src/redux/notices/notices-slice.js
=> 240 notices fix

src/components/Notices/Favorite/Favorite.jsx, src/components/Notices/Favorite/NotAdded/NotAdded.jsx, src/components/Notices/addPet/NoticesAddPet.jsx, src/components/Notices/categories/NoticesCategories.jsx, src/components/Notices/heading/NoticesHeading.jsx, src/components/Notices/items/NoticesItems.jsx, src/components/Notices/learnMore/Buttons/AddTo/AddTo.jsx, src/components/Notices/learnMore/Buttons/Buttons.jsx, src/components/Notices/learnMore/Buttons/RemoveFrom/RemoveFrom.jsx, src/components/Notices/learnMore/LearnMore.jsx, src/components/Notices/list/NoticesList.jsx, src/components/Notices/pagination/paginationBtn/PaginationBtn.jsx, src/components/Notices/search/NoticesSearch.jsx, src/pages/NoticesPage/NoticesPage.jsx
=> finish section Notices

src/pages/HomePage/HomePage.module.scss
=> Header fix
